name: Django CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: "Arthur Ochilo"
          POSTGRES_USER: "hd4h3hh2xxxx"
          POSTGRES_PASSWORD: "ggsh@ajak23xxx"
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://g1g34hjfu7748gssaf43wd:shsjjaja@localhost:5432/ArthurOchilo98
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
